// components/SamplePdfCarousel.jsx
"use client";

import Image from "next/image";

export default function SamplePdfCarousel() {
  const images = [
    {
      src: "/samples/social-studies-pdf.png",
      alt: "Social Studies TEKS worksheet sample",
      label: "Social Studies",
      detail: "Printable practice",
    },
    {
      src: "/samples/grammar-pdf.png",
      alt: "Grammar TEKS worksheet sample",
      label: "Grammar",
      detail: "Language conventions",
    },
    {
      src: "/samples/reading-pdf.png",
      alt: "Reading comprehension TEKS worksheet sample",
      label: "Reading",
      detail: "Comprehension skills",
    },
    {
      src: "/samples/grammar2-pdf.png",
      alt: "Grammar worksheet sample",
      label: "Grammar",
      detail: "Editing practice",
    },
  ];

  return (
<section
  className="
  py-20
  overflow-hidden
  bg-gradient-to-b
  from-purple-50
  via-white
  to-purple-50
"
>      
<div
className="
max-w-7xl
mx-auto
px-8
text-center
rounded-[40px]
py-16
bg-white/80
backdrop-blur-sm
border
border-purple-100
"
>        {/* Header */}
        <p className="text-primary font-semibold mb-3">
          Printable Practice Library
        </p>

        <h2 className="text-3xl sm:text-4xl font-extrabold text-base-content tracking-tight">
          Turn TEKS skills into classroom-ready worksheets
        </h2>

        <p className="text-base-content/70 max-w-3xl mx-auto mt-4 mb-12">
          Preview printable practice generated by subject, grade level,
          and skill focus.
        </p>

        {/* Carousel */}
        <div className="relative max-w-6xl mx-auto overflow-hidden">
          {/* fade edges */}
          <div className="pointer-events-none absolute left-0 top-0 h-full w-20 bg-gradient-to-r from-base-100 to-transparent z-10" />

          <div className="pointer-events-none absolute right-0 top-0 h-full w-20 bg-gradient-to-l from-base-100 to-transparent z-10" />

          <div className="flex flex-nowrap whitespace-nowrap animate-scroll gap-6 py-4">
            {[...images, ...images].map((img, i) => (
              <div
                key={i}
                className="
                  min-w-[260px]
                  text-left
                "
              >
                <div
                  className="
                    rounded-3xl
                    overflow-hidden
                    border
                    hover:shadow-xl
                    transition-all
                    duration-300
                    p-3
                    bg-white
                    border-purple-100
                    shadow-md
                    hover:shadow-2xl
                  "
                >
                  <Image
                    src={img.src}
                    alt={img.alt}
                    width={260}
                    height={380}
                    className="
                      w-full
                      object-cover
                      rounded-2xl
                    "
                  />
                </div>

                {/* Caption */}
                <div className="mt-4 px-1">
                  <p className="font-bold text-base-content">
                    {img.label}
                  </p>

                  <p className="text-sm text-base-content/60">
                    {img.detail}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Footer note */}
        <p className="text-sm text-base-content/60 mt-10">
          Generate printable practice instantly or download polished PDFs for classroom use.
        </p>
      </div>
    </section>
  );
}

// return (
//   <section className="bg-gradient-to-b from-purple-700 via-purple-600 to-purple-500 text-neutral-content">
//     <div className=" px-8 py-4 md:py-14 text-center">
//       {/* SEO-Friendly Heading */}{" "}
//       <h2 className="flex sm:text-4xl font-semi-bold text-white/90 py-4 tracking-light">
//         {" "}
//         Featured Sample Worksheets{" "}
//       </h2>{" "}
//       {/* Carousel Wrapper */}{" "}
//       <div
//         className="relative p-4 rounded-xl w-full overflow-hidden"
//         onMouseEnter={stopAutoSlide}
//         onMouseLeave={startAutoSlide}
//       >
//         {" "}
//         {/* Slider Track */}{" "}
//         <div
//           className={`flex max-w-6xl mx-auto ${isTransitioning ? "transition-transform duration-700 ease-out" : ""}`}
//           style={{
//             transform: `translateX(-${index * 28}%)`,
//             width: `${loopImages.length * 28}%`,
//           }}
//         >
//           {" "}
//           {loopImages.map((img, i) => (
//             <div key={i} className="snap-x w-1/4 px-2 flex-shrink-0 ">
//               {" "}
//               <div className="relative rounded-lg overflow-hidden ">
//                 {" "}
//                 <Image
//                   src={img.src}
//                   alt={img.alt}
//                   width={260}
//                   height={380}
//                   className="snap-center w-full object-cover rounded-lg border-2 border-purple-800 shadow-2xl"
//                 />{" "}
//                 {/* <div className="absolute inset-0 bg-gradient-to-t from-black/20 to-transparent"></div> */}
//                 {/* <div className="absolute inset-0 bg-black opacity-10"></div> */}
//                 {/* Caption */}
//                 <p className="text-left text-white/90 text-md mt-2 ml-1">
//                   {img.label}
//                 </p>
//               </div>{" "}
//             </div>
//           ))}{" "}
//         </div>{" "}
//         {/* Left Button */}{" "}
//         {/* <button
//             onClick={prev}
//             className="absolute left-3 top-1/2 -translate-y-1/2 bg-purple-200 hover:bg-purple-300 text-purple-800 px-3 py-2 rounded-full shadow"
//           >
//             {" "}
//             ‹{" "}
//           </button>{" "} */}
//         {/* Right Button */}{" "}
//         {/* <button
//             onClick={next}
//             className="absolute right-3 top-1/2 -translate-y-1/2 bg-purple-200 hover:bg-purple-300 text-purple-800 px-3 py-2 rounded-full shadow"
//           >
//             {" "}
//             ›{" "}
//           </button>{" "} */}
//       </div>{" "}
//       {/* Dots */}{" "}
//       <div className="flex justify-center mt-4 gap-2">
//         {" "}
//         {images.map((_, i) => (
//           <button
//             key={i}
//             onClick={() => setIndex(i)}
//             className={`h-3 w-3 rounded-full transition-all ${index === i ? "bg-purple-300 scale-110" : "bg-gray-300"}`}
//           />
//         ))}{" "}
//       </div>{" "}
//     </div>
//   </section>
// );
